name: Solar System Workflow
on: [workflow_dispatch, push]
env:
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: UTest
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18 
            - name: Insall Dependencies
              run: npm install
            - name: Unit Testing
              run: npm test   
            
            - name: Archive Test Results
              uses: actions/upload-artifact@v3
              with:
                name: Mocha-Test-Results
                path: test-results.xml
