name: Solar System Workflow
on: [workflow_dispatch, push]

jobs:
    unit-testing:
        name: UTest
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Setup NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18 
            - name: Insall Dependencies
              run: npm install
            - name: Unit Testing
              run: npm test   
